public class SECTORES_WORKING {
    String NOMBRETRABAJADOR, PROFESION_TRABAJADOR, EDAD_TRABAJADOR;



    public SECTORES_WORKING (String NOMBRETRABAJADOR, String PROFESION_TRABAJADOR, String EDAD_TRABAJADOR){
        this.NOMBRETRABAJADOR = NOMBRETRABAJADOR;
        this.PROFESION_TRABAJADOR = PROFESION_TRABAJADOR;
        this.EDAD_TRABAJADOR = EDAD_TRABAJADOR;
    }

    public String OBTENER_NAME_WORK(){
        return NOMBRETRABAJADOR;
    }
    public String OBTENER_PROFESION_WORK(){
        return PROFESION_TRABAJADOR;
    }
    public String OBTENER_EDAD_WORK(){
        return EDAD_TRABAJADOR;
    }

    
}
